# config.yaml
dataset:
  images_dir: 'images'
  masks_dir: 'masks'
  transform:
    resize: [224, 224]
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]

model:
  type: 'UNet'
  learning_rate: 0.0001

training:
  batch_size: 32
  num_epochs: 50
  train_test_split_ratio: 0.8

device:
  use_cuda: true

paths:
  model_save_path: 'encoder_decoder.pt'
